/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressRow: typeof import('./src/components/address/address-row.vue')['default']
    CartList: typeof import('./src/components/cart/cart-list.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    OrderRow: typeof import('./src/components/order/order-row.vue')['default']
    ProductCover: typeof import('./src/components/product/product-cover.vue')['default']
    ProductRow: typeof import('./src/components/product/product-row.vue')['default']
    ProductSkuDialogCopy: typeof import('./src/components/product/product-sku-dialog-copy.vue')['default']
    UserAvatar: typeof import('./src/components/user/user-avatar.vue')['default']
  }
}
