/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    ProductCover: typeof import('./src/components/product/product-cover.vue')['default']
    ProductSkuDialog: typeof import('./src/components/product/product-sku-dialog.vue')['default']
    UserAvatar: typeof import('./src/components/user/user-avatar.vue')['default']
  }
}
